HEAD:
  mixed-port: 7890
  allow-lan: true
  mode: rule
  log-level: info
  external-controller: :9090
  dns:
    enable: true
    listen: 0.0.0.0:1053
    default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
    nameserver-policy:
      geosite:gfw,geolocation-!cn:
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query
      - https://8.8.8.8/dns-query
    nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://8.8.8.8/dns-query
    fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://8.8.8.8/dns-query
    fallback-filter:
      geoip: false
      geoip-code: CN
      ipcidr:
      - 240.0.0.0/4
    fake-ip-filter:
    - +.lan
    - +.microsoft*.com
    - localhost.ptlogin2.qq.com
  rule-providers:
    direct:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
      path: ./ruleset/direct.yaml
      interval: 86400
    cncidr:
      type: http
      behavior: ipcidr
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
      path: ./ruleset/cncidr.yaml
      interval: 86400
    lancidr:
      type: http
      behavior: ipcidr
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
      path: ./ruleset/lancidr.yaml
      interval: 86400
    gfw:
      type: http
      behavior: domain
      url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
      path: ./ruleset/gfw.yaml
      interval: 86400
  rules:
    - DOMAIN,cdn.jsdelivr.net,DIRECT
    - RULE-SET,direct,DIRECT
    - RULE-SET,cncidr,DIRECT
    - RULE-SET,lancidr,DIRECT
    - GEOIP,CN,DIRECT
    - RULE-SET,gfw,PROXY
    - DOMAIN-KEYWORD,docker,PROXY
    - DOMAIN-KEYWORD,dockerhub,PROXY
    - MATCH,FALLBACK
TEST_URL: https://www.gstatic.com/generate_204
RULESET: []
CUSTOM_PROXY_GROUP:
  - name: PROXY
    type: select
    proxies:
      - FALLBACK
      - SELECT
      - URL-TEST
      - DIRECT
  - name: FALLBACK
    type: fallback
    interval: 300
    lazy: true
    tolerance: 100
    proxies:
      - DIRECT
      - URL-TEST
  - name: URL-TEST
    type: url-test
    interval: 600
    lazy: true
    tolerance: 100
  - name: SELECT
    type: select
